/********************************************************************************
** Form generated from reading UI file 'dialog_customcan.ui'
**
** Created by: Qt User Interface Compiler version 5.14.2
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_DIALOG_CUSTOMCAN_H
#define UI_DIALOG_CUSTOMCAN_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QCheckBox>
#include <QtWidgets/QComboBox>
#include <QtWidgets/QDialog>
#include <QtWidgets/QFrame>
#include <QtWidgets/QLabel>
#include <QtWidgets/QLineEdit>
#include <QtWidgets/QPushButton>

QT_BEGIN_NAMESPACE

class Ui_Dialog_CustomCan
{
public:
    QComboBox *ComboBox_DataFormat;
    QFrame *frame_4;
    QComboBox *ComboBox_VehicleSpd_SignalName;
    QLineEdit *LineEdit_VehicleSpd_Length;
    QLabel *label_22;
    QLabel *label_20;
    QLineEdit *LineEdit_VehicleSpd_Start;
    QLabel *label_21;
    QComboBox *ComboBox_VehicleSpd_UorI;
    QLineEdit *LineEdit_VehicleSpd_Factor;
    QLineEdit *LineEdit_VehicleSpd_ID;
    QCheckBox *CheckBox_VehicleSpd_En;
    QLabel *label_19;
    QLabel *Label_VehicleSpd;
    QLabel *label_24;
    QLabel *label_23;
    QLineEdit *LineEdit_VehicleSpd_Offset;
    QComboBox *ComboBox_VehicleSpd_ID;
    QLabel *label_25;
    QLineEdit *LineEdit_VehicleSpd_Unit;
    QLabel *label_14;
    QLabel *label_13;
    QFrame *frame_5;
    QComboBox *ComboBox_FLWheelSpd_SignalName;
    QLineEdit *LineEdit_FLWheelSpd_Length;
    QLabel *label_26;
    QLabel *label_27;
    QLineEdit *LineEdit_FLWheelSpd_Start;
    QLabel *label_28;
    QComboBox *ComboBox_FLWheelSpd_UorI;
    QLineEdit *LineEdit_FLWheelSpd_Offset;
    QLineEdit *LineEdit_FLWheelSpd_ID;
    QCheckBox *CheckBox_FLWheelSpd_En;
    QLabel *label_30;
    QLabel *Label_FLWheelSpd;
    QLabel *label_50;
    QLabel *label_29;
    QLineEdit *LineEdit_FLWheelSpd_Factor;
    QComboBox *ComboBox_FLWheelSpd_ID;
    QLabel *label_36;
    QLineEdit *LineEdit_FLWheelSpd_Unit;
    QFrame *frame_9;
    QComboBox *ComboBox_FRWheelSpd_SignalName;
    QLineEdit *LineEdit_FRWheelSpd_Length;
    QLabel *label_51;
    QLabel *label_52;
    QLineEdit *LineEdit_FRWheelSpd_Start;
    QLabel *label_53;
    QComboBox *ComboBox_FRWheelSpd_UorI;
    QLineEdit *LineEdit_FRWheelSpd_Offset;
    QLineEdit *LineEdit_FRWheelSpd_ID;
    QCheckBox *CheckBox_FRWheelSpd_En;
    QLabel *label_55;
    QLabel *Label_FRWheelSpd;
    QLabel *label_57;
    QLabel *label_54;
    QLineEdit *LineEdit_FRWheelSpd_Factor;
    QComboBox *ComboBox_FRWheelSpd_ID;
    QLabel *label_40;
    QLineEdit *LineEdit_FRWheelSpd_Unit;
    QFrame *frame_10;
    QComboBox *ComboBox_RLWheelSpd_SignalName;
    QLineEdit *LineEdit_RLWheelSpd_Length;
    QLabel *label_58;
    QLabel *label_59;
    QLineEdit *LineEdit_RLWheelSpd_Start;
    QLabel *label_60;
    QComboBox *ComboBox_RLWheelSpd_UorI;
    QLineEdit *LineEdit_RLWheelSpd_Offset;
    QLineEdit *LineEdit_RLWheelSpd_ID;
    QCheckBox *CheckBox_RLWheelSpd_En;
    QLabel *label_62;
    QLabel *Label_RLWheelSpd;
    QLabel *label_64;
    QLabel *label_61;
    QLineEdit *LineEdit_RLWheelSpd_Factor;
    QComboBox *ComboBox_RLWheelSpd_ID;
    QLineEdit *LineEdit_RLWheelSpd_Unit;
    QLabel *label_38;
    QFrame *frame_11;
    QComboBox *ComboBox_RRWheelSpd_SignalName;
    QLineEdit *LineEdit_RRWheelSpd_Length;
    QLabel *label_65;
    QLabel *label_66;
    QLineEdit *LineEdit_RRWheelSpd_Start;
    QLabel *label_67;
    QComboBox *ComboBox_RRWheelSpd_UorI;
    QLineEdit *LineEdit_RRWheelSpd_Offset;
    QLineEdit *LineEdit_RRWheelSpd_ID;
    QCheckBox *CheckBox_RRWheelSpd_En;
    QLabel *label_69;
    QLabel *Label_RRWheelSpd;
    QLabel *label_71;
    QLineEdit *LineEdit_RRWheelSpd_Factor;
    QLabel *label_68;
    QComboBox *ComboBox_RRWheelSpd_ID;
    QLabel *label_39;
    QLineEdit *LineEdit_RRWheelSpd_Unit;
    QFrame *frame_6;
    QComboBox *ComboBox_Gear_SignalName;
    QLabel *label_31;
    QLabel *label_32;
    QLineEdit *LineEdit_Gear_Start;
    QLabel *label_34;
    QComboBox *ComboBox_Gear_UorI;
    QLineEdit *LineEdit_Gear_Offset;
    QLineEdit *LineEdit_Gear_ID;
    QCheckBox *CheckBox_Gear_En;
    QLabel *label_35;
    QLabel *Label_Gear;
    QLabel *label_37;
    QLineEdit *LineEdit_Gear_Factor;
    QLineEdit *LineEdit_Gear_P;
    QCheckBox *CheckBox_Gear_PEN;
    QLineEdit *LineEdit_Gear_D;
    QCheckBox *CheckBox_Gear_DEN;
    QCheckBox *CheckBox_Gear_REN;
    QLineEdit *LineEdit_Gear_R;
    QLineEdit *LineEdit_Gear_N;
    QCheckBox *CheckBox_Gear_NEN;
    QLabel *label_33;
    QLineEdit *LineEdit_Gear_Length;
    QComboBox *ComboBox_Gear_ID;
    QLabel *label_41;
    QLineEdit *LineEdit_Gear_Unit;
    QFrame *frame;
    QPushButton *PushButton_SendCAN;
    QCheckBox *CheckBox_DBCInput;
    QPushButton *PushButton_ReadDBC;
    QCheckBox *CheckBox_ManualInput;

    void setupUi(QDialog *Dialog_CustomCan)
    {
        if (Dialog_CustomCan->objectName().isEmpty())
            Dialog_CustomCan->setObjectName(QString::fromUtf8("Dialog_CustomCan"));
        Dialog_CustomCan->resize(1261, 541);
        Dialog_CustomCan->setMinimumSize(QSize(1261, 541));
        Dialog_CustomCan->setMaximumSize(QSize(1261, 541));
        ComboBox_DataFormat = new QComboBox(Dialog_CustomCan);
        ComboBox_DataFormat->addItem(QString());
        ComboBox_DataFormat->addItem(QString());
        ComboBox_DataFormat->setObjectName(QString::fromUtf8("ComboBox_DataFormat"));
        ComboBox_DataFormat->setGeometry(QRect(1120, 20, 121, 31));
        QFont font;
        font.setPointSize(12);
        ComboBox_DataFormat->setFont(font);
        frame_4 = new QFrame(Dialog_CustomCan);
        frame_4->setObjectName(QString::fromUtf8("frame_4"));
        frame_4->setGeometry(QRect(10, 140, 621, 131));
        frame_4->setFrameShape(QFrame::Box);
        frame_4->setFrameShadow(QFrame::Plain);
        ComboBox_VehicleSpd_SignalName = new QComboBox(frame_4);
        ComboBox_VehicleSpd_SignalName->setObjectName(QString::fromUtf8("ComboBox_VehicleSpd_SignalName"));
        ComboBox_VehicleSpd_SignalName->setGeometry(QRect(460, 10, 151, 30));
        QFont font1;
        font1.setPointSize(9);
        ComboBox_VehicleSpd_SignalName->setFont(font1);
        LineEdit_VehicleSpd_Length = new QLineEdit(frame_4);
        LineEdit_VehicleSpd_Length->setObjectName(QString::fromUtf8("LineEdit_VehicleSpd_Length"));
        LineEdit_VehicleSpd_Length->setGeometry(QRect(510, 50, 100, 30));
        QFont font2;
        font2.setPointSize(11);
        LineEdit_VehicleSpd_Length->setFont(font2);
        LineEdit_VehicleSpd_Length->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_22 = new QLabel(frame_4);
        label_22->setObjectName(QString::fromUtf8("label_22"));
        label_22->setGeometry(QRect(421, 90, 90, 30));
        QFont font3;
        font3.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font3.setPointSize(11);
        label_22->setFont(font3);
        label_20 = new QLabel(frame_4);
        label_20->setObjectName(QString::fromUtf8("label_20"));
        label_20->setGeometry(QRect(211, 50, 90, 30));
        label_20->setFont(font3);
        LineEdit_VehicleSpd_Start = new QLineEdit(frame_4);
        LineEdit_VehicleSpd_Start->setObjectName(QString::fromUtf8("LineEdit_VehicleSpd_Start"));
        LineEdit_VehicleSpd_Start->setGeometry(QRect(300, 50, 100, 30));
        LineEdit_VehicleSpd_Start->setFont(font2);
        LineEdit_VehicleSpd_Start->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_21 = new QLabel(frame_4);
        label_21->setObjectName(QString::fromUtf8("label_21"));
        label_21->setGeometry(QRect(420, 50, 90, 30));
        label_21->setFont(font3);
        ComboBox_VehicleSpd_UorI = new QComboBox(frame_4);
        ComboBox_VehicleSpd_UorI->addItem(QString());
        ComboBox_VehicleSpd_UorI->addItem(QString());
        ComboBox_VehicleSpd_UorI->setObjectName(QString::fromUtf8("ComboBox_VehicleSpd_UorI"));
        ComboBox_VehicleSpd_UorI->setGeometry(QRect(100, 50, 100, 30));
        ComboBox_VehicleSpd_UorI->setFont(font2);
        LineEdit_VehicleSpd_Factor = new QLineEdit(frame_4);
        LineEdit_VehicleSpd_Factor->setObjectName(QString::fromUtf8("LineEdit_VehicleSpd_Factor"));
        LineEdit_VehicleSpd_Factor->setGeometry(QRect(300, 90, 100, 30));
        LineEdit_VehicleSpd_Factor->setFont(font2);
        LineEdit_VehicleSpd_Factor->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LineEdit_VehicleSpd_ID = new QLineEdit(frame_4);
        LineEdit_VehicleSpd_ID->setObjectName(QString::fromUtf8("LineEdit_VehicleSpd_ID"));
        LineEdit_VehicleSpd_ID->setGeometry(QRect(230, 10, 151, 30));
        LineEdit_VehicleSpd_ID->setFont(font2);
        LineEdit_VehicleSpd_ID->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_VehicleSpd_En = new QCheckBox(frame_4);
        CheckBox_VehicleSpd_En->setObjectName(QString::fromUtf8("CheckBox_VehicleSpd_En"));
        CheckBox_VehicleSpd_En->setGeometry(QRect(11, 10, 231, 31));
        QFont font4;
        font4.setPointSize(13);
        CheckBox_VehicleSpd_En->setFont(font4);
        label_19 = new QLabel(frame_4);
        label_19->setObjectName(QString::fromUtf8("label_19"));
        label_19->setGeometry(QRect(10, 50, 90, 30));
        label_19->setFont(font3);
        Label_VehicleSpd = new QLabel(frame_4);
        Label_VehicleSpd->setObjectName(QString::fromUtf8("Label_VehicleSpd"));
        Label_VehicleSpd->setGeometry(QRect(390, 10, 90, 30));
        Label_VehicleSpd->setFont(font3);
        label_24 = new QLabel(frame_4);
        label_24->setObjectName(QString::fromUtf8("label_24"));
        label_24->setGeometry(QRect(155, 10, 81, 30));
        label_24->setFont(font3);
        label_23 = new QLabel(frame_4);
        label_23->setObjectName(QString::fromUtf8("label_23"));
        label_23->setGeometry(QRect(210, 90, 90, 30));
        label_23->setFont(font3);
        LineEdit_VehicleSpd_Offset = new QLineEdit(frame_4);
        LineEdit_VehicleSpd_Offset->setObjectName(QString::fromUtf8("LineEdit_VehicleSpd_Offset"));
        LineEdit_VehicleSpd_Offset->setGeometry(QRect(510, 90, 100, 30));
        LineEdit_VehicleSpd_Offset->setFont(font2);
        LineEdit_VehicleSpd_Offset->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ComboBox_VehicleSpd_ID = new QComboBox(frame_4);
        ComboBox_VehicleSpd_ID->setObjectName(QString::fromUtf8("ComboBox_VehicleSpd_ID"));
        ComboBox_VehicleSpd_ID->setGeometry(QRect(230, 10, 151, 31));
        label_25 = new QLabel(frame_4);
        label_25->setObjectName(QString::fromUtf8("label_25"));
        label_25->setGeometry(QRect(11, 90, 90, 30));
        label_25->setFont(font3);
        LineEdit_VehicleSpd_Unit = new QLineEdit(frame_4);
        LineEdit_VehicleSpd_Unit->setObjectName(QString::fromUtf8("LineEdit_VehicleSpd_Unit"));
        LineEdit_VehicleSpd_Unit->setGeometry(QRect(100, 90, 100, 30));
        LineEdit_VehicleSpd_Unit->setFont(font2);
        LineEdit_VehicleSpd_Unit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_14 = new QLabel(Dialog_CustomCan);
        label_14->setObjectName(QString::fromUtf8("label_14"));
        label_14->setGeometry(QRect(1020, 20, 90, 30));
        label_14->setFont(font3);
        label_13 = new QLabel(Dialog_CustomCan);
        label_13->setObjectName(QString::fromUtf8("label_13"));
        label_13->setGeometry(QRect(470, 0, 321, 61));
        QFont font5;
        font5.setFamily(QString::fromUtf8("\345\276\256\350\275\257\351\233\205\351\273\221"));
        font5.setPointSize(16);
        label_13->setFont(font5);
        label_13->setAlignment(Qt::AlignCenter);
        frame_5 = new QFrame(Dialog_CustomCan);
        frame_5->setObjectName(QString::fromUtf8("frame_5"));
        frame_5->setGeometry(QRect(10, 270, 621, 131));
        frame_5->setFrameShape(QFrame::Box);
        frame_5->setFrameShadow(QFrame::Plain);
        ComboBox_FLWheelSpd_SignalName = new QComboBox(frame_5);
        ComboBox_FLWheelSpd_SignalName->setObjectName(QString::fromUtf8("ComboBox_FLWheelSpd_SignalName"));
        ComboBox_FLWheelSpd_SignalName->setGeometry(QRect(460, 10, 151, 30));
        ComboBox_FLWheelSpd_SignalName->setFont(font1);
        LineEdit_FLWheelSpd_Length = new QLineEdit(frame_5);
        LineEdit_FLWheelSpd_Length->setObjectName(QString::fromUtf8("LineEdit_FLWheelSpd_Length"));
        LineEdit_FLWheelSpd_Length->setGeometry(QRect(510, 50, 100, 30));
        LineEdit_FLWheelSpd_Length->setFont(font2);
        LineEdit_FLWheelSpd_Length->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_26 = new QLabel(frame_5);
        label_26->setObjectName(QString::fromUtf8("label_26"));
        label_26->setGeometry(QRect(421, 90, 90, 30));
        label_26->setFont(font3);
        label_27 = new QLabel(frame_5);
        label_27->setObjectName(QString::fromUtf8("label_27"));
        label_27->setGeometry(QRect(211, 50, 90, 30));
        label_27->setFont(font3);
        LineEdit_FLWheelSpd_Start = new QLineEdit(frame_5);
        LineEdit_FLWheelSpd_Start->setObjectName(QString::fromUtf8("LineEdit_FLWheelSpd_Start"));
        LineEdit_FLWheelSpd_Start->setGeometry(QRect(300, 50, 100, 30));
        LineEdit_FLWheelSpd_Start->setFont(font2);
        LineEdit_FLWheelSpd_Start->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_28 = new QLabel(frame_5);
        label_28->setObjectName(QString::fromUtf8("label_28"));
        label_28->setGeometry(QRect(420, 50, 90, 30));
        label_28->setFont(font3);
        ComboBox_FLWheelSpd_UorI = new QComboBox(frame_5);
        ComboBox_FLWheelSpd_UorI->addItem(QString());
        ComboBox_FLWheelSpd_UorI->addItem(QString());
        ComboBox_FLWheelSpd_UorI->setObjectName(QString::fromUtf8("ComboBox_FLWheelSpd_UorI"));
        ComboBox_FLWheelSpd_UorI->setGeometry(QRect(100, 50, 100, 30));
        ComboBox_FLWheelSpd_UorI->setFont(font2);
        LineEdit_FLWheelSpd_Offset = new QLineEdit(frame_5);
        LineEdit_FLWheelSpd_Offset->setObjectName(QString::fromUtf8("LineEdit_FLWheelSpd_Offset"));
        LineEdit_FLWheelSpd_Offset->setGeometry(QRect(510, 90, 100, 30));
        LineEdit_FLWheelSpd_Offset->setFont(font2);
        LineEdit_FLWheelSpd_Offset->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LineEdit_FLWheelSpd_ID = new QLineEdit(frame_5);
        LineEdit_FLWheelSpd_ID->setObjectName(QString::fromUtf8("LineEdit_FLWheelSpd_ID"));
        LineEdit_FLWheelSpd_ID->setGeometry(QRect(230, 10, 151, 30));
        LineEdit_FLWheelSpd_ID->setFont(font2);
        LineEdit_FLWheelSpd_ID->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_FLWheelSpd_En = new QCheckBox(frame_5);
        CheckBox_FLWheelSpd_En->setObjectName(QString::fromUtf8("CheckBox_FLWheelSpd_En"));
        CheckBox_FLWheelSpd_En->setGeometry(QRect(11, 10, 231, 31));
        CheckBox_FLWheelSpd_En->setFont(font4);
        label_30 = new QLabel(frame_5);
        label_30->setObjectName(QString::fromUtf8("label_30"));
        label_30->setGeometry(QRect(10, 50, 90, 30));
        label_30->setFont(font3);
        Label_FLWheelSpd = new QLabel(frame_5);
        Label_FLWheelSpd->setObjectName(QString::fromUtf8("Label_FLWheelSpd"));
        Label_FLWheelSpd->setGeometry(QRect(390, 10, 90, 30));
        Label_FLWheelSpd->setFont(font3);
        label_50 = new QLabel(frame_5);
        label_50->setObjectName(QString::fromUtf8("label_50"));
        label_50->setGeometry(QRect(155, 10, 81, 30));
        label_50->setFont(font3);
        label_29 = new QLabel(frame_5);
        label_29->setObjectName(QString::fromUtf8("label_29"));
        label_29->setGeometry(QRect(210, 90, 90, 30));
        label_29->setFont(font3);
        LineEdit_FLWheelSpd_Factor = new QLineEdit(frame_5);
        LineEdit_FLWheelSpd_Factor->setObjectName(QString::fromUtf8("LineEdit_FLWheelSpd_Factor"));
        LineEdit_FLWheelSpd_Factor->setGeometry(QRect(300, 90, 100, 30));
        LineEdit_FLWheelSpd_Factor->setFont(font2);
        LineEdit_FLWheelSpd_Factor->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ComboBox_FLWheelSpd_ID = new QComboBox(frame_5);
        ComboBox_FLWheelSpd_ID->setObjectName(QString::fromUtf8("ComboBox_FLWheelSpd_ID"));
        ComboBox_FLWheelSpd_ID->setGeometry(QRect(230, 10, 151, 31));
        label_36 = new QLabel(frame_5);
        label_36->setObjectName(QString::fromUtf8("label_36"));
        label_36->setGeometry(QRect(11, 90, 90, 30));
        label_36->setFont(font3);
        LineEdit_FLWheelSpd_Unit = new QLineEdit(frame_5);
        LineEdit_FLWheelSpd_Unit->setObjectName(QString::fromUtf8("LineEdit_FLWheelSpd_Unit"));
        LineEdit_FLWheelSpd_Unit->setGeometry(QRect(100, 90, 100, 30));
        LineEdit_FLWheelSpd_Unit->setFont(font2);
        LineEdit_FLWheelSpd_Unit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_9 = new QFrame(Dialog_CustomCan);
        frame_9->setObjectName(QString::fromUtf8("frame_9"));
        frame_9->setGeometry(QRect(630, 270, 621, 131));
        frame_9->setFrameShape(QFrame::Box);
        frame_9->setFrameShadow(QFrame::Plain);
        ComboBox_FRWheelSpd_SignalName = new QComboBox(frame_9);
        ComboBox_FRWheelSpd_SignalName->setObjectName(QString::fromUtf8("ComboBox_FRWheelSpd_SignalName"));
        ComboBox_FRWheelSpd_SignalName->setGeometry(QRect(460, 10, 151, 30));
        ComboBox_FRWheelSpd_SignalName->setFont(font1);
        LineEdit_FRWheelSpd_Length = new QLineEdit(frame_9);
        LineEdit_FRWheelSpd_Length->setObjectName(QString::fromUtf8("LineEdit_FRWheelSpd_Length"));
        LineEdit_FRWheelSpd_Length->setGeometry(QRect(510, 50, 100, 30));
        LineEdit_FRWheelSpd_Length->setFont(font2);
        LineEdit_FRWheelSpd_Length->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_51 = new QLabel(frame_9);
        label_51->setObjectName(QString::fromUtf8("label_51"));
        label_51->setGeometry(QRect(421, 90, 90, 30));
        label_51->setFont(font3);
        label_52 = new QLabel(frame_9);
        label_52->setObjectName(QString::fromUtf8("label_52"));
        label_52->setGeometry(QRect(211, 50, 90, 30));
        label_52->setFont(font3);
        LineEdit_FRWheelSpd_Start = new QLineEdit(frame_9);
        LineEdit_FRWheelSpd_Start->setObjectName(QString::fromUtf8("LineEdit_FRWheelSpd_Start"));
        LineEdit_FRWheelSpd_Start->setGeometry(QRect(300, 50, 100, 30));
        LineEdit_FRWheelSpd_Start->setFont(font2);
        LineEdit_FRWheelSpd_Start->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_53 = new QLabel(frame_9);
        label_53->setObjectName(QString::fromUtf8("label_53"));
        label_53->setGeometry(QRect(420, 50, 90, 30));
        label_53->setFont(font3);
        ComboBox_FRWheelSpd_UorI = new QComboBox(frame_9);
        ComboBox_FRWheelSpd_UorI->addItem(QString());
        ComboBox_FRWheelSpd_UorI->addItem(QString());
        ComboBox_FRWheelSpd_UorI->setObjectName(QString::fromUtf8("ComboBox_FRWheelSpd_UorI"));
        ComboBox_FRWheelSpd_UorI->setGeometry(QRect(100, 50, 100, 30));
        ComboBox_FRWheelSpd_UorI->setFont(font2);
        LineEdit_FRWheelSpd_Offset = new QLineEdit(frame_9);
        LineEdit_FRWheelSpd_Offset->setObjectName(QString::fromUtf8("LineEdit_FRWheelSpd_Offset"));
        LineEdit_FRWheelSpd_Offset->setGeometry(QRect(510, 90, 100, 30));
        LineEdit_FRWheelSpd_Offset->setFont(font2);
        LineEdit_FRWheelSpd_Offset->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LineEdit_FRWheelSpd_ID = new QLineEdit(frame_9);
        LineEdit_FRWheelSpd_ID->setObjectName(QString::fromUtf8("LineEdit_FRWheelSpd_ID"));
        LineEdit_FRWheelSpd_ID->setGeometry(QRect(230, 10, 151, 30));
        LineEdit_FRWheelSpd_ID->setFont(font2);
        LineEdit_FRWheelSpd_ID->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_FRWheelSpd_En = new QCheckBox(frame_9);
        CheckBox_FRWheelSpd_En->setObjectName(QString::fromUtf8("CheckBox_FRWheelSpd_En"));
        CheckBox_FRWheelSpd_En->setGeometry(QRect(11, 10, 231, 31));
        CheckBox_FRWheelSpd_En->setFont(font4);
        label_55 = new QLabel(frame_9);
        label_55->setObjectName(QString::fromUtf8("label_55"));
        label_55->setGeometry(QRect(10, 50, 90, 30));
        label_55->setFont(font3);
        Label_FRWheelSpd = new QLabel(frame_9);
        Label_FRWheelSpd->setObjectName(QString::fromUtf8("Label_FRWheelSpd"));
        Label_FRWheelSpd->setGeometry(QRect(390, 10, 90, 30));
        Label_FRWheelSpd->setFont(font3);
        label_57 = new QLabel(frame_9);
        label_57->setObjectName(QString::fromUtf8("label_57"));
        label_57->setGeometry(QRect(155, 10, 81, 30));
        label_57->setFont(font3);
        label_54 = new QLabel(frame_9);
        label_54->setObjectName(QString::fromUtf8("label_54"));
        label_54->setGeometry(QRect(210, 90, 90, 30));
        label_54->setFont(font3);
        LineEdit_FRWheelSpd_Factor = new QLineEdit(frame_9);
        LineEdit_FRWheelSpd_Factor->setObjectName(QString::fromUtf8("LineEdit_FRWheelSpd_Factor"));
        LineEdit_FRWheelSpd_Factor->setGeometry(QRect(300, 90, 100, 30));
        LineEdit_FRWheelSpd_Factor->setFont(font2);
        LineEdit_FRWheelSpd_Factor->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ComboBox_FRWheelSpd_ID = new QComboBox(frame_9);
        ComboBox_FRWheelSpd_ID->setObjectName(QString::fromUtf8("ComboBox_FRWheelSpd_ID"));
        ComboBox_FRWheelSpd_ID->setGeometry(QRect(230, 10, 151, 31));
        label_40 = new QLabel(frame_9);
        label_40->setObjectName(QString::fromUtf8("label_40"));
        label_40->setGeometry(QRect(11, 90, 90, 30));
        label_40->setFont(font3);
        LineEdit_FRWheelSpd_Unit = new QLineEdit(frame_9);
        LineEdit_FRWheelSpd_Unit->setObjectName(QString::fromUtf8("LineEdit_FRWheelSpd_Unit"));
        LineEdit_FRWheelSpd_Unit->setGeometry(QRect(100, 90, 100, 30));
        LineEdit_FRWheelSpd_Unit->setFont(font2);
        LineEdit_FRWheelSpd_Unit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_10 = new QFrame(Dialog_CustomCan);
        frame_10->setObjectName(QString::fromUtf8("frame_10"));
        frame_10->setGeometry(QRect(10, 400, 621, 131));
        frame_10->setFrameShape(QFrame::Box);
        frame_10->setFrameShadow(QFrame::Plain);
        ComboBox_RLWheelSpd_SignalName = new QComboBox(frame_10);
        ComboBox_RLWheelSpd_SignalName->setObjectName(QString::fromUtf8("ComboBox_RLWheelSpd_SignalName"));
        ComboBox_RLWheelSpd_SignalName->setGeometry(QRect(460, 10, 151, 30));
        ComboBox_RLWheelSpd_SignalName->setFont(font1);
        LineEdit_RLWheelSpd_Length = new QLineEdit(frame_10);
        LineEdit_RLWheelSpd_Length->setObjectName(QString::fromUtf8("LineEdit_RLWheelSpd_Length"));
        LineEdit_RLWheelSpd_Length->setGeometry(QRect(510, 50, 100, 30));
        LineEdit_RLWheelSpd_Length->setFont(font2);
        LineEdit_RLWheelSpd_Length->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_58 = new QLabel(frame_10);
        label_58->setObjectName(QString::fromUtf8("label_58"));
        label_58->setGeometry(QRect(421, 90, 90, 30));
        label_58->setFont(font3);
        label_59 = new QLabel(frame_10);
        label_59->setObjectName(QString::fromUtf8("label_59"));
        label_59->setGeometry(QRect(211, 50, 90, 30));
        label_59->setFont(font3);
        LineEdit_RLWheelSpd_Start = new QLineEdit(frame_10);
        LineEdit_RLWheelSpd_Start->setObjectName(QString::fromUtf8("LineEdit_RLWheelSpd_Start"));
        LineEdit_RLWheelSpd_Start->setGeometry(QRect(300, 50, 100, 30));
        LineEdit_RLWheelSpd_Start->setFont(font2);
        LineEdit_RLWheelSpd_Start->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_60 = new QLabel(frame_10);
        label_60->setObjectName(QString::fromUtf8("label_60"));
        label_60->setGeometry(QRect(420, 50, 90, 30));
        label_60->setFont(font3);
        ComboBox_RLWheelSpd_UorI = new QComboBox(frame_10);
        ComboBox_RLWheelSpd_UorI->addItem(QString());
        ComboBox_RLWheelSpd_UorI->addItem(QString());
        ComboBox_RLWheelSpd_UorI->setObjectName(QString::fromUtf8("ComboBox_RLWheelSpd_UorI"));
        ComboBox_RLWheelSpd_UorI->setGeometry(QRect(100, 50, 100, 30));
        ComboBox_RLWheelSpd_UorI->setFont(font2);
        LineEdit_RLWheelSpd_Offset = new QLineEdit(frame_10);
        LineEdit_RLWheelSpd_Offset->setObjectName(QString::fromUtf8("LineEdit_RLWheelSpd_Offset"));
        LineEdit_RLWheelSpd_Offset->setGeometry(QRect(510, 90, 100, 30));
        LineEdit_RLWheelSpd_Offset->setFont(font2);
        LineEdit_RLWheelSpd_Offset->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LineEdit_RLWheelSpd_ID = new QLineEdit(frame_10);
        LineEdit_RLWheelSpd_ID->setObjectName(QString::fromUtf8("LineEdit_RLWheelSpd_ID"));
        LineEdit_RLWheelSpd_ID->setGeometry(QRect(230, 10, 151, 30));
        LineEdit_RLWheelSpd_ID->setFont(font2);
        LineEdit_RLWheelSpd_ID->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_RLWheelSpd_En = new QCheckBox(frame_10);
        CheckBox_RLWheelSpd_En->setObjectName(QString::fromUtf8("CheckBox_RLWheelSpd_En"));
        CheckBox_RLWheelSpd_En->setGeometry(QRect(11, 10, 231, 31));
        CheckBox_RLWheelSpd_En->setFont(font4);
        label_62 = new QLabel(frame_10);
        label_62->setObjectName(QString::fromUtf8("label_62"));
        label_62->setGeometry(QRect(10, 50, 90, 30));
        label_62->setFont(font3);
        Label_RLWheelSpd = new QLabel(frame_10);
        Label_RLWheelSpd->setObjectName(QString::fromUtf8("Label_RLWheelSpd"));
        Label_RLWheelSpd->setGeometry(QRect(390, 10, 90, 30));
        Label_RLWheelSpd->setFont(font3);
        label_64 = new QLabel(frame_10);
        label_64->setObjectName(QString::fromUtf8("label_64"));
        label_64->setGeometry(QRect(155, 10, 81, 30));
        label_64->setFont(font3);
        label_61 = new QLabel(frame_10);
        label_61->setObjectName(QString::fromUtf8("label_61"));
        label_61->setGeometry(QRect(210, 90, 90, 30));
        label_61->setFont(font3);
        LineEdit_RLWheelSpd_Factor = new QLineEdit(frame_10);
        LineEdit_RLWheelSpd_Factor->setObjectName(QString::fromUtf8("LineEdit_RLWheelSpd_Factor"));
        LineEdit_RLWheelSpd_Factor->setGeometry(QRect(300, 90, 100, 30));
        LineEdit_RLWheelSpd_Factor->setFont(font2);
        LineEdit_RLWheelSpd_Factor->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ComboBox_RLWheelSpd_ID = new QComboBox(frame_10);
        ComboBox_RLWheelSpd_ID->setObjectName(QString::fromUtf8("ComboBox_RLWheelSpd_ID"));
        ComboBox_RLWheelSpd_ID->setGeometry(QRect(230, 10, 151, 31));
        ComboBox_RLWheelSpd_ID->setFrame(true);
        LineEdit_RLWheelSpd_Unit = new QLineEdit(frame_10);
        LineEdit_RLWheelSpd_Unit->setObjectName(QString::fromUtf8("LineEdit_RLWheelSpd_Unit"));
        LineEdit_RLWheelSpd_Unit->setGeometry(QRect(100, 90, 100, 30));
        LineEdit_RLWheelSpd_Unit->setFont(font2);
        LineEdit_RLWheelSpd_Unit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_38 = new QLabel(frame_10);
        label_38->setObjectName(QString::fromUtf8("label_38"));
        label_38->setGeometry(QRect(11, 90, 90, 30));
        label_38->setFont(font3);
        frame_11 = new QFrame(Dialog_CustomCan);
        frame_11->setObjectName(QString::fromUtf8("frame_11"));
        frame_11->setGeometry(QRect(630, 400, 621, 131));
        frame_11->setFrameShape(QFrame::Box);
        frame_11->setFrameShadow(QFrame::Plain);
        ComboBox_RRWheelSpd_SignalName = new QComboBox(frame_11);
        ComboBox_RRWheelSpd_SignalName->setObjectName(QString::fromUtf8("ComboBox_RRWheelSpd_SignalName"));
        ComboBox_RRWheelSpd_SignalName->setGeometry(QRect(460, 10, 151, 30));
        ComboBox_RRWheelSpd_SignalName->setFont(font1);
        LineEdit_RRWheelSpd_Length = new QLineEdit(frame_11);
        LineEdit_RRWheelSpd_Length->setObjectName(QString::fromUtf8("LineEdit_RRWheelSpd_Length"));
        LineEdit_RRWheelSpd_Length->setGeometry(QRect(510, 50, 100, 30));
        LineEdit_RRWheelSpd_Length->setFont(font2);
        LineEdit_RRWheelSpd_Length->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_65 = new QLabel(frame_11);
        label_65->setObjectName(QString::fromUtf8("label_65"));
        label_65->setGeometry(QRect(421, 90, 90, 30));
        label_65->setFont(font3);
        label_66 = new QLabel(frame_11);
        label_66->setObjectName(QString::fromUtf8("label_66"));
        label_66->setGeometry(QRect(211, 50, 90, 30));
        label_66->setFont(font3);
        LineEdit_RRWheelSpd_Start = new QLineEdit(frame_11);
        LineEdit_RRWheelSpd_Start->setObjectName(QString::fromUtf8("LineEdit_RRWheelSpd_Start"));
        LineEdit_RRWheelSpd_Start->setGeometry(QRect(300, 50, 100, 30));
        LineEdit_RRWheelSpd_Start->setFont(font2);
        LineEdit_RRWheelSpd_Start->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_67 = new QLabel(frame_11);
        label_67->setObjectName(QString::fromUtf8("label_67"));
        label_67->setGeometry(QRect(420, 50, 90, 30));
        label_67->setFont(font3);
        ComboBox_RRWheelSpd_UorI = new QComboBox(frame_11);
        ComboBox_RRWheelSpd_UorI->addItem(QString());
        ComboBox_RRWheelSpd_UorI->addItem(QString());
        ComboBox_RRWheelSpd_UorI->setObjectName(QString::fromUtf8("ComboBox_RRWheelSpd_UorI"));
        ComboBox_RRWheelSpd_UorI->setGeometry(QRect(100, 50, 100, 30));
        ComboBox_RRWheelSpd_UorI->setFont(font2);
        LineEdit_RRWheelSpd_Offset = new QLineEdit(frame_11);
        LineEdit_RRWheelSpd_Offset->setObjectName(QString::fromUtf8("LineEdit_RRWheelSpd_Offset"));
        LineEdit_RRWheelSpd_Offset->setGeometry(QRect(510, 90, 100, 30));
        LineEdit_RRWheelSpd_Offset->setFont(font2);
        LineEdit_RRWheelSpd_Offset->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LineEdit_RRWheelSpd_ID = new QLineEdit(frame_11);
        LineEdit_RRWheelSpd_ID->setObjectName(QString::fromUtf8("LineEdit_RRWheelSpd_ID"));
        LineEdit_RRWheelSpd_ID->setGeometry(QRect(230, 10, 151, 30));
        LineEdit_RRWheelSpd_ID->setFont(font2);
        LineEdit_RRWheelSpd_ID->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_RRWheelSpd_En = new QCheckBox(frame_11);
        CheckBox_RRWheelSpd_En->setObjectName(QString::fromUtf8("CheckBox_RRWheelSpd_En"));
        CheckBox_RRWheelSpd_En->setGeometry(QRect(11, 10, 231, 31));
        CheckBox_RRWheelSpd_En->setFont(font4);
        label_69 = new QLabel(frame_11);
        label_69->setObjectName(QString::fromUtf8("label_69"));
        label_69->setGeometry(QRect(10, 50, 90, 30));
        label_69->setFont(font3);
        Label_RRWheelSpd = new QLabel(frame_11);
        Label_RRWheelSpd->setObjectName(QString::fromUtf8("Label_RRWheelSpd"));
        Label_RRWheelSpd->setGeometry(QRect(390, 10, 90, 30));
        Label_RRWheelSpd->setFont(font3);
        label_71 = new QLabel(frame_11);
        label_71->setObjectName(QString::fromUtf8("label_71"));
        label_71->setGeometry(QRect(155, 10, 81, 30));
        label_71->setFont(font3);
        LineEdit_RRWheelSpd_Factor = new QLineEdit(frame_11);
        LineEdit_RRWheelSpd_Factor->setObjectName(QString::fromUtf8("LineEdit_RRWheelSpd_Factor"));
        LineEdit_RRWheelSpd_Factor->setGeometry(QRect(300, 90, 100, 30));
        LineEdit_RRWheelSpd_Factor->setFont(font2);
        LineEdit_RRWheelSpd_Factor->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_68 = new QLabel(frame_11);
        label_68->setObjectName(QString::fromUtf8("label_68"));
        label_68->setGeometry(QRect(210, 90, 90, 30));
        label_68->setFont(font3);
        ComboBox_RRWheelSpd_ID = new QComboBox(frame_11);
        ComboBox_RRWheelSpd_ID->setObjectName(QString::fromUtf8("ComboBox_RRWheelSpd_ID"));
        ComboBox_RRWheelSpd_ID->setGeometry(QRect(230, 10, 151, 31));
        label_39 = new QLabel(frame_11);
        label_39->setObjectName(QString::fromUtf8("label_39"));
        label_39->setGeometry(QRect(11, 90, 90, 30));
        label_39->setFont(font3);
        LineEdit_RRWheelSpd_Unit = new QLineEdit(frame_11);
        LineEdit_RRWheelSpd_Unit->setObjectName(QString::fromUtf8("LineEdit_RRWheelSpd_Unit"));
        LineEdit_RRWheelSpd_Unit->setGeometry(QRect(100, 90, 100, 30));
        LineEdit_RRWheelSpd_Unit->setFont(font2);
        LineEdit_RRWheelSpd_Unit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame_6 = new QFrame(Dialog_CustomCan);
        frame_6->setObjectName(QString::fromUtf8("frame_6"));
        frame_6->setGeometry(QRect(630, 60, 621, 211));
        frame_6->setFrameShape(QFrame::Box);
        frame_6->setFrameShadow(QFrame::Plain);
        ComboBox_Gear_SignalName = new QComboBox(frame_6);
        ComboBox_Gear_SignalName->setObjectName(QString::fromUtf8("ComboBox_Gear_SignalName"));
        ComboBox_Gear_SignalName->setGeometry(QRect(460, 10, 151, 30));
        ComboBox_Gear_SignalName->setFont(font1);
        label_31 = new QLabel(frame_6);
        label_31->setObjectName(QString::fromUtf8("label_31"));
        label_31->setGeometry(QRect(421, 90, 90, 30));
        label_31->setFont(font3);
        label_32 = new QLabel(frame_6);
        label_32->setObjectName(QString::fromUtf8("label_32"));
        label_32->setGeometry(QRect(211, 50, 90, 30));
        label_32->setFont(font3);
        LineEdit_Gear_Start = new QLineEdit(frame_6);
        LineEdit_Gear_Start->setObjectName(QString::fromUtf8("LineEdit_Gear_Start"));
        LineEdit_Gear_Start->setGeometry(QRect(300, 50, 100, 30));
        LineEdit_Gear_Start->setFont(font2);
        LineEdit_Gear_Start->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        label_34 = new QLabel(frame_6);
        label_34->setObjectName(QString::fromUtf8("label_34"));
        label_34->setGeometry(QRect(210, 90, 90, 30));
        label_34->setFont(font3);
        ComboBox_Gear_UorI = new QComboBox(frame_6);
        ComboBox_Gear_UorI->addItem(QString());
        ComboBox_Gear_UorI->addItem(QString());
        ComboBox_Gear_UorI->setObjectName(QString::fromUtf8("ComboBox_Gear_UorI"));
        ComboBox_Gear_UorI->setGeometry(QRect(100, 50, 100, 30));
        ComboBox_Gear_UorI->setFont(font2);
        LineEdit_Gear_Offset = new QLineEdit(frame_6);
        LineEdit_Gear_Offset->setObjectName(QString::fromUtf8("LineEdit_Gear_Offset"));
        LineEdit_Gear_Offset->setGeometry(QRect(511, 90, 100, 30));
        LineEdit_Gear_Offset->setFont(font2);
        LineEdit_Gear_Offset->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LineEdit_Gear_ID = new QLineEdit(frame_6);
        LineEdit_Gear_ID->setObjectName(QString::fromUtf8("LineEdit_Gear_ID"));
        LineEdit_Gear_ID->setGeometry(QRect(230, 10, 151, 30));
        LineEdit_Gear_ID->setFont(font2);
        LineEdit_Gear_ID->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_Gear_En = new QCheckBox(frame_6);
        CheckBox_Gear_En->setObjectName(QString::fromUtf8("CheckBox_Gear_En"));
        CheckBox_Gear_En->setGeometry(QRect(11, 10, 231, 31));
        CheckBox_Gear_En->setFont(font4);
        label_35 = new QLabel(frame_6);
        label_35->setObjectName(QString::fromUtf8("label_35"));
        label_35->setGeometry(QRect(10, 50, 90, 30));
        label_35->setFont(font3);
        Label_Gear = new QLabel(frame_6);
        Label_Gear->setObjectName(QString::fromUtf8("Label_Gear"));
        Label_Gear->setGeometry(QRect(390, 10, 90, 30));
        Label_Gear->setFont(font3);
        label_37 = new QLabel(frame_6);
        label_37->setObjectName(QString::fromUtf8("label_37"));
        label_37->setGeometry(QRect(155, 10, 81, 30));
        label_37->setFont(font3);
        LineEdit_Gear_Factor = new QLineEdit(frame_6);
        LineEdit_Gear_Factor->setObjectName(QString::fromUtf8("LineEdit_Gear_Factor"));
        LineEdit_Gear_Factor->setGeometry(QRect(300, 90, 100, 30));
        LineEdit_Gear_Factor->setFont(font2);
        LineEdit_Gear_Factor->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LineEdit_Gear_P = new QLineEdit(frame_6);
        LineEdit_Gear_P->setObjectName(QString::fromUtf8("LineEdit_Gear_P"));
        LineEdit_Gear_P->setEnabled(false);
        LineEdit_Gear_P->setGeometry(QRect(160, 130, 131, 30));
        LineEdit_Gear_P->setFont(font2);
        LineEdit_Gear_P->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_Gear_PEN = new QCheckBox(frame_6);
        CheckBox_Gear_PEN->setObjectName(QString::fromUtf8("CheckBox_Gear_PEN"));
        CheckBox_Gear_PEN->setGeometry(QRect(20, 130, 101, 31));
        CheckBox_Gear_PEN->setFont(font2);
        LineEdit_Gear_D = new QLineEdit(frame_6);
        LineEdit_Gear_D->setObjectName(QString::fromUtf8("LineEdit_Gear_D"));
        LineEdit_Gear_D->setEnabled(false);
        LineEdit_Gear_D->setGeometry(QRect(479, 130, 131, 30));
        LineEdit_Gear_D->setFont(font2);
        LineEdit_Gear_D->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_Gear_DEN = new QCheckBox(frame_6);
        CheckBox_Gear_DEN->setObjectName(QString::fromUtf8("CheckBox_Gear_DEN"));
        CheckBox_Gear_DEN->setGeometry(QRect(350, 130, 101, 31));
        CheckBox_Gear_DEN->setFont(font2);
        CheckBox_Gear_REN = new QCheckBox(frame_6);
        CheckBox_Gear_REN->setObjectName(QString::fromUtf8("CheckBox_Gear_REN"));
        CheckBox_Gear_REN->setGeometry(QRect(20, 170, 101, 31));
        CheckBox_Gear_REN->setFont(font2);
        LineEdit_Gear_R = new QLineEdit(frame_6);
        LineEdit_Gear_R->setObjectName(QString::fromUtf8("LineEdit_Gear_R"));
        LineEdit_Gear_R->setEnabled(false);
        LineEdit_Gear_R->setGeometry(QRect(160, 170, 131, 30));
        LineEdit_Gear_R->setFont(font2);
        LineEdit_Gear_R->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        LineEdit_Gear_N = new QLineEdit(frame_6);
        LineEdit_Gear_N->setObjectName(QString::fromUtf8("LineEdit_Gear_N"));
        LineEdit_Gear_N->setEnabled(false);
        LineEdit_Gear_N->setGeometry(QRect(480, 170, 131, 30));
        LineEdit_Gear_N->setFont(font2);
        LineEdit_Gear_N->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        CheckBox_Gear_NEN = new QCheckBox(frame_6);
        CheckBox_Gear_NEN->setObjectName(QString::fromUtf8("CheckBox_Gear_NEN"));
        CheckBox_Gear_NEN->setGeometry(QRect(350, 170, 101, 31));
        CheckBox_Gear_NEN->setFont(font2);
        label_33 = new QLabel(frame_6);
        label_33->setObjectName(QString::fromUtf8("label_33"));
        label_33->setGeometry(QRect(420, 50, 90, 30));
        label_33->setFont(font3);
        LineEdit_Gear_Length = new QLineEdit(frame_6);
        LineEdit_Gear_Length->setObjectName(QString::fromUtf8("LineEdit_Gear_Length"));
        LineEdit_Gear_Length->setGeometry(QRect(510, 50, 100, 30));
        LineEdit_Gear_Length->setFont(font2);
        LineEdit_Gear_Length->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        ComboBox_Gear_ID = new QComboBox(frame_6);
        ComboBox_Gear_ID->setObjectName(QString::fromUtf8("ComboBox_Gear_ID"));
        ComboBox_Gear_ID->setGeometry(QRect(230, 10, 151, 31));
        label_41 = new QLabel(frame_6);
        label_41->setObjectName(QString::fromUtf8("label_41"));
        label_41->setGeometry(QRect(11, 90, 90, 30));
        label_41->setFont(font3);
        LineEdit_Gear_Unit = new QLineEdit(frame_6);
        LineEdit_Gear_Unit->setObjectName(QString::fromUtf8("LineEdit_Gear_Unit"));
        LineEdit_Gear_Unit->setGeometry(QRect(100, 90, 100, 30));
        LineEdit_Gear_Unit->setFont(font2);
        LineEdit_Gear_Unit->setAlignment(Qt::AlignRight|Qt::AlignTrailing|Qt::AlignVCenter);
        frame = new QFrame(Dialog_CustomCan);
        frame->setObjectName(QString::fromUtf8("frame"));
        frame->setGeometry(QRect(10, 60, 621, 81));
        frame->setFrameShape(QFrame::Box);
        frame->setFrameShadow(QFrame::Plain);
        PushButton_SendCAN = new QPushButton(frame);
        PushButton_SendCAN->setObjectName(QString::fromUtf8("PushButton_SendCAN"));
        PushButton_SendCAN->setGeometry(QRect(300, 20, 311, 51));
        PushButton_SendCAN->setFont(font2);
        CheckBox_DBCInput = new QCheckBox(frame);
        CheckBox_DBCInput->setObjectName(QString::fromUtf8("CheckBox_DBCInput"));
        CheckBox_DBCInput->setGeometry(QRect(10, 50, 121, 19));
        CheckBox_DBCInput->setAutoExclusive(true);
        PushButton_ReadDBC = new QPushButton(frame);
        PushButton_ReadDBC->setObjectName(QString::fromUtf8("PushButton_ReadDBC"));
        PushButton_ReadDBC->setEnabled(false);
        PushButton_ReadDBC->setGeometry(QRect(160, 20, 111, 51));
        PushButton_ReadDBC->setFont(font2);
        CheckBox_ManualInput = new QCheckBox(frame);
        CheckBox_ManualInput->setObjectName(QString::fromUtf8("CheckBox_ManualInput"));
        CheckBox_ManualInput->setGeometry(QRect(10, 20, 121, 19));
        CheckBox_ManualInput->setChecked(true);
        CheckBox_ManualInput->setAutoExclusive(true);

        retranslateUi(Dialog_CustomCan);

        ComboBox_VehicleSpd_SignalName->setCurrentIndex(-1);
        ComboBox_FLWheelSpd_SignalName->setCurrentIndex(-1);
        ComboBox_FRWheelSpd_SignalName->setCurrentIndex(-1);
        ComboBox_RLWheelSpd_SignalName->setCurrentIndex(-1);
        ComboBox_RRWheelSpd_SignalName->setCurrentIndex(-1);
        ComboBox_Gear_SignalName->setCurrentIndex(-1);


        QMetaObject::connectSlotsByName(Dialog_CustomCan);
    } // setupUi

    void retranslateUi(QDialog *Dialog_CustomCan)
    {
        Dialog_CustomCan->setWindowTitle(QCoreApplication::translate("Dialog_CustomCan", "Dialog", nullptr));
        ComboBox_DataFormat->setItemText(0, QCoreApplication::translate("Dialog_CustomCan", "Motorola", nullptr));
        ComboBox_DataFormat->setItemText(1, QCoreApplication::translate("Dialog_CustomCan", "Inter", nullptr));

        label_22->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\201\217\347\247\273\351\207\217:", nullptr));
        label_20->setText(QCoreApplication::translate("Dialog_CustomCan", "\350\265\267\345\247\213\344\275\215:", nullptr));
        label_21->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\351\225\277\345\272\246:", nullptr));
        ComboBox_VehicleSpd_UorI->setItemText(0, QCoreApplication::translate("Dialog_CustomCan", "\346\227\240\347\254\246\345\217\267\346\225\260", nullptr));
        ComboBox_VehicleSpd_UorI->setItemText(1, QCoreApplication::translate("Dialog_CustomCan", "\346\234\211\347\254\246\345\217\267\346\225\260", nullptr));

        LineEdit_VehicleSpd_Factor->setText(QString());
        LineEdit_VehicleSpd_ID->setText(QString());
        CheckBox_VehicleSpd_En->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\261\275\350\275\246\350\275\246\351\200\237", nullptr));
        label_19->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\347\261\273\345\236\213:", nullptr));
        Label_VehicleSpd->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\220\215:", nullptr));
        label_24->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\270\247ID:  0x", nullptr));
        label_23->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\257\224\344\276\213\347\263\273\346\225\260:", nullptr));
        label_25->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\215\225\344\275\215:", nullptr));
        label_14->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\346\240\274\345\274\217:", nullptr));
        label_13->setText(QCoreApplication::translate("Dialog_CustomCan", "\350\207\252\345\256\232\344\271\211\345\272\225\347\233\230CAN", nullptr));
        label_26->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\201\217\347\247\273\351\207\217:", nullptr));
        label_27->setText(QCoreApplication::translate("Dialog_CustomCan", "\350\265\267\345\247\213\344\275\215:", nullptr));
        label_28->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\351\225\277\345\272\246:", nullptr));
        ComboBox_FLWheelSpd_UorI->setItemText(0, QCoreApplication::translate("Dialog_CustomCan", "\346\227\240\347\254\246\345\217\267\346\225\260", nullptr));
        ComboBox_FLWheelSpd_UorI->setItemText(1, QCoreApplication::translate("Dialog_CustomCan", "\346\234\211\347\254\246\345\217\267\346\225\260", nullptr));

        LineEdit_FLWheelSpd_Offset->setText(QString());
        LineEdit_FLWheelSpd_ID->setText(QString());
        CheckBox_FLWheelSpd_En->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\267\246\345\211\215\350\275\256\351\200\237", nullptr));
        label_30->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\347\261\273\345\236\213:", nullptr));
        Label_FLWheelSpd->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\220\215:", nullptr));
        label_50->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\270\247ID:  0x", nullptr));
        label_29->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\257\224\344\276\213\347\263\273\346\225\260:", nullptr));
        label_36->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\215\225\344\275\215:", nullptr));
        label_51->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\201\217\347\247\273\351\207\217:", nullptr));
        label_52->setText(QCoreApplication::translate("Dialog_CustomCan", "\350\265\267\345\247\213\344\275\215:", nullptr));
        label_53->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\351\225\277\345\272\246:", nullptr));
        ComboBox_FRWheelSpd_UorI->setItemText(0, QCoreApplication::translate("Dialog_CustomCan", "\346\227\240\347\254\246\345\217\267\346\225\260", nullptr));
        ComboBox_FRWheelSpd_UorI->setItemText(1, QCoreApplication::translate("Dialog_CustomCan", "\346\234\211\347\254\246\345\217\267\346\225\260", nullptr));

        LineEdit_FRWheelSpd_Offset->setText(QString());
        LineEdit_FRWheelSpd_ID->setText(QString());
        CheckBox_FRWheelSpd_En->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\217\263\345\211\215\350\275\256\351\200\237", nullptr));
        label_55->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\347\261\273\345\236\213:", nullptr));
        Label_FRWheelSpd->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\220\215:", nullptr));
        label_57->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\270\247ID:  0x", nullptr));
        label_54->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\257\224\344\276\213\347\263\273\346\225\260:", nullptr));
        label_40->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\215\225\344\275\215:", nullptr));
        label_58->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\201\217\347\247\273\351\207\217:", nullptr));
        label_59->setText(QCoreApplication::translate("Dialog_CustomCan", "\350\265\267\345\247\213\344\275\215:", nullptr));
        label_60->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\351\225\277\345\272\246:", nullptr));
        ComboBox_RLWheelSpd_UorI->setItemText(0, QCoreApplication::translate("Dialog_CustomCan", "\346\227\240\347\254\246\345\217\267\346\225\260", nullptr));
        ComboBox_RLWheelSpd_UorI->setItemText(1, QCoreApplication::translate("Dialog_CustomCan", "\346\234\211\347\254\246\345\217\267\346\225\260", nullptr));

        LineEdit_RLWheelSpd_Offset->setText(QString());
        LineEdit_RLWheelSpd_ID->setText(QString());
        CheckBox_RLWheelSpd_En->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\267\246\345\220\216\350\275\256\351\200\237", nullptr));
        label_62->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\347\261\273\345\236\213:", nullptr));
        Label_RLWheelSpd->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\220\215:", nullptr));
        label_64->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\270\247ID:  0x", nullptr));
        label_61->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\257\224\344\276\213\347\263\273\346\225\260:", nullptr));
        label_38->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\215\225\344\275\215:", nullptr));
        label_65->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\201\217\347\247\273\351\207\217:", nullptr));
        label_66->setText(QCoreApplication::translate("Dialog_CustomCan", "\350\265\267\345\247\213\344\275\215:", nullptr));
        label_67->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\351\225\277\345\272\246:", nullptr));
        ComboBox_RRWheelSpd_UorI->setItemText(0, QCoreApplication::translate("Dialog_CustomCan", "\346\227\240\347\254\246\345\217\267\346\225\260", nullptr));
        ComboBox_RRWheelSpd_UorI->setItemText(1, QCoreApplication::translate("Dialog_CustomCan", "\346\234\211\347\254\246\345\217\267\346\225\260", nullptr));

        LineEdit_RRWheelSpd_Offset->setText(QString());
        LineEdit_RRWheelSpd_ID->setText(QString());
        CheckBox_RRWheelSpd_En->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\217\263\345\220\216\350\275\256\351\200\237", nullptr));
        label_69->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\347\261\273\345\236\213:", nullptr));
        Label_RRWheelSpd->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\220\215:", nullptr));
        label_71->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\270\247ID:  0x", nullptr));
        label_68->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\257\224\344\276\213\347\263\273\346\225\260:", nullptr));
        label_39->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\215\225\344\275\215:", nullptr));
        label_31->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\201\217\347\247\273\351\207\217:", nullptr));
        label_32->setText(QCoreApplication::translate("Dialog_CustomCan", "\350\265\267\345\247\213\344\275\215:", nullptr));
        label_34->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\257\224\344\276\213\347\263\273\346\225\260:", nullptr));
        ComboBox_Gear_UorI->setItemText(0, QCoreApplication::translate("Dialog_CustomCan", "\346\227\240\347\254\246\345\217\267\346\225\260", nullptr));
        ComboBox_Gear_UorI->setItemText(1, QCoreApplication::translate("Dialog_CustomCan", "\346\234\211\347\254\246\345\217\267\346\225\260", nullptr));

        LineEdit_Gear_Offset->setText(QString());
        LineEdit_Gear_ID->setText(QString());
        CheckBox_Gear_En->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\261\275\350\275\246\346\214\241\344\275\215", nullptr));
        label_35->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\347\261\273\345\236\213:", nullptr));
        Label_Gear->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\220\215:", nullptr));
        label_37->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\270\247ID:  0x", nullptr));
        LineEdit_Gear_Factor->setText(QString());
        LineEdit_Gear_P->setText(QString());
        CheckBox_Gear_PEN->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\201\234\350\275\246\346\241\243\345\200\274:", nullptr));
        LineEdit_Gear_D->setText(QString());
        CheckBox_Gear_DEN->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\211\215\350\277\233\346\241\243\345\200\274:", nullptr));
        CheckBox_Gear_REN->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\200\222\350\275\246\346\241\243\345\200\274:", nullptr));
        LineEdit_Gear_R->setText(QString());
        LineEdit_Gear_N->setText(QString());
        CheckBox_Gear_NEN->setText(QCoreApplication::translate("Dialog_CustomCan", "\347\251\272\346\241\243\345\200\274:", nullptr));
        label_33->setText(QCoreApplication::translate("Dialog_CustomCan", "\346\225\260\346\215\256\351\225\277\345\272\246:", nullptr));
        label_41->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\277\241\345\217\267\345\215\225\344\275\215:", nullptr));
        PushButton_SendCAN->setText(QCoreApplication::translate("Dialog_CustomCan", "\345\217\221\351\200\201\350\207\252\345\256\232\344\271\211CAN", nullptr));
        CheckBox_DBCInput->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\273\245DBC\350\276\223\345\205\245", nullptr));
        PushButton_ReadDBC->setText(QCoreApplication::translate("Dialog_CustomCan", "\350\257\273\345\217\226DBC\346\226\207\344\273\266", nullptr));
        CheckBox_ManualInput->setText(QCoreApplication::translate("Dialog_CustomCan", "\344\273\245\346\211\213\345\212\250\350\276\223\345\205\245", nullptr));
    } // retranslateUi

};

namespace Ui {
    class Dialog_CustomCan: public Ui_Dialog_CustomCan {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_DIALOG_CUSTOMCAN_H
